name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deployment is not configured
        run: echo "Choose between Heroku and Azure then delete this step (uncomment steps bellow accordingly)."

#    # Deploy and release to Heroku.
#    steps:
#      - name: Create SHA Container Tag
#        id: sha_tag
#        run: |
#          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
#          echo "::set-output name=tag::$tag"
#
#      - name: Login to Github Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN  }}
#
#      - name: Login to Heroku Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: registry.heroku.com
#          username: _
#          password: ${{ secrets.HEROKU_API_KEY }}
#
#      - name: Push Image to Heroku
#        uses: akhilerm/tag-push-action@v2.0.0
#        with:
#          src: ghcr.io/${{ github.repository }}:${{ steps.sha_tag.outputs.tag }}
#          dst: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/worker
#
#      - name: Authenticate to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          justlogin: true
#
#      - name: Release to Heroku
#        run: |
#          heroku container:login
#          heroku container:release worker -a ${{ secrets.HEROKU_APP_NAME }}

#    # Deploy and release to Azure.
#    steps:
#      - name: Deploy to Azure Web App
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ secrets.AZURE_APP_NAME }}
#          slot-name: ${{ secrets.AZURE_SLOT_NAME }}
#          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#          images: ghcr.io/${{ github.repository }}:${{ steps.sha_tag.outputs.tag }}
